dist: focal
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # See https://github.com/konstantint/matplotlib-venn/issues/76
  # - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - which python
  - python -m venv venv
  - source venv/bin/activate
  - pip install -e .
  - pip install pytest

script:
  - py.test
