dist: focal
language: python
python:
  - "2.7"
  #- "3.4" # Not available in the 20.04 Ubuntu image
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - which python
  - python -m venv venv
  - source venv/bin/activate
  - pip install -e .

script:
  - py.test
